--  migrations/                # SQL files for setting up the database schema
--     ├── create_users_table.sql # SQL for creating the users table
--     ├── create_sessions_table.sql # SQL for creating the session table
--     └── create_feedback_table.sql # SQL for feedback and AI analysis